# INTRODUCTIONS
:welcome: "-----------------------------------------------------
\nWelcome to Twenty-One! We're shuffling the deck now..
\n-----------------------------------------------------"

:lets_play_again: "----------------------------------------------------
                 \n                (:  LET'S PLAY AGAIN!  :)
                 \n----------------------------------------------------"

# HIT OR STAY?
:hit_or_stay: "              -------------------------
               \n--------------| HIT or STAY? (H or S) |--------------
               \n              -------------------------"

#GAME DECISIONS
:player_hits: "You chose to HIT"
:player_stays: "You chose to STAY"
:dealer_hits: "Dealer chooses to HIT"
:dealer_stays: "Dealer chooses to STAY"

# ROUND WINNER DECLARATIONS
:player_busted: "\n----------------------------------------------------
                 \n                ):  YOU BUSTED  :(
                 \n----------------------------------------------------"

:dealer_busted: "\n----------------------------------------------------
                 \n         :D   DEALER BUSTED -- YOU WIN! :D
                 \n----------------------------------------------------
                 \n\n _._     _,-'\"\"`-._      <-- CELEBRATION CAT!
                 \n(,-.`._,'(       |\\`-/|
                 \n    `-.-' \\ )-`( , o o)
                 \n         `-    \\`_`\"'-
                 \n"

:tie: "\n----------------------------------------------------
                 \n     O:   You're both winners - it's a tie!  :O
                 \n----------------------------------------------------"

:dealer_won: "\n----------------------------------------------------
                 \n               ),:  DEALER WON  :,(
                 \n----------------------------------------------------"

:player_won: "\n----------------------------------------------------
                 \n >>>>>>>>>>>>>>  :D  YOU WON!!!  :D   <<<<<<<<<<<<<<
                 \n----------------------------------------------------
                  \n\n _._     _,-'\"\"`-._      <-- CELEBRATION CAT!
                    \n(,-.`._,'(       |\\`-/|
                    \n    `-.-' \\ )-`( , o o)
                    \n         `-    \\`_`\"'-
                    \n"

# PLAY AGAIN?
:play_again: "<>.><o><o><o><o><o><o><o><><o><o><o><o><o><o><o><.<>
                 \n<<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>>
                 \n><.><                                          ><.><   
                 \n<>.<>    Do you want to play again?  (Y / N)   <>.<> 
                 \n><.><                                          ><.><   
                 \n<<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>><<>>
                 \n<>.><o><o><o><o><o><o><><o><o><o><o><o><o><o><o><.<>"

# THANKS FOR PLAYING!
:thanks_for_playing: "\n  (: (: (: THANKS FOR PLAYING TWENTY-ONE! :) :) :)\n\n"
